# Generated by Django 4.2.5 on 2023-09-12 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
