# Generated by Django 4.2.5 on 2023-09-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0006_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
