# Generated by Django 4.2.5 on 2023-09-18 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0014_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='category_id',
        ),
    ]
