# Generated by Django 4.2.5 on 2023-09-18 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0015_rename_category_product_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
    ]
