# Generated by Django 4.2.5 on 2023-09-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0020_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_approval',
            field=models.BooleanField(default=False),
        ),
    ]
