# Generated by Django 4.2.5 on 2023-09-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0022_remove_userprofile_is_approval_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityprofile',
            name='is_approval',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_approval',
            field=models.BooleanField(default=False),
        ),
    ]
