# Generated by Django 4.2.5 on 2023-10-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0026_alter_billinginformation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinginformation',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
