# Generated by Django 4.2.5 on 2023-10-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0031_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='community_is_approved',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
