# Generated by Django 4.2.5 on 2023-10-10 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0032_product_community_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='community_is_approved',
        ),
    ]
