# Generated by Django 4.2.5 on 2023-10-10 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0033_remove_product_community_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='giftapp.communityprofile'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(default='1', max_length=200),
        ),
    ]
