# Generated by Django 4.2.5 on 2023-10-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftapp', '0034_product_community_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityprofile',
            name='certification_image',
            field=models.ImageField(blank=True, null=True, upload_to='certification_image/'),
        ),
        migrations.AddField(
            model_name='communityprofile',
            name='community_is_approved',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
