# Generated by Django 4.2.5 on 2024-02-06 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('giftapp', '0035_communityprofile_certification_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinginformation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
